# Generated by Django 4.1.7 on 2023-03-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('release_date', models.DateField(blank=True)),
                ('lte_exists', models.BooleanField(blank=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
